hdl_localization:
  ros__parameters:
    # basic parameters
    points_topic: "/livox/lidar"
    imu_topic: "/livox/imu"
    localization_odom_frame_id: "base_link"
    odom_child_frame_id: "livox_frame"
    
    # topic name
    odom_topic: "/odom/ground_truth"        #"/odom/ground_truth"   /odom/localization_odom 
    aligned_points_topic: "/aligned_points"
    status_topic: "/status"
    localization_info_topic: "/localization_info"
    global_map_points_topic: "/global_map_points"

    # IMU parameters
    use_imu: true
    invert_acc: false
    invert_gyro: false

    # global localization parameters
    use_global_localization: false

    # odometry prediction parameters
    enable_robot_odometry_prediction: false
    robot_odom_frame_id: "odom"

    # numeric parameters
    imu_data_filter_num: 5
    globalmap_voxel_size: 0.3
    points_voxel_filter_size: 0.2

    # other parameters
    cool_time_duration: 0.1

    # registration method parameters
    reg_method: "NDT_OMP"
    ndt_neighbor_search_method: "DIRECT7"
    ndt_neighbor_search_radius: 1.0
    ndt_resolution: 0.5
    downsample_resolution: 0.1

    # initial pose parameters
    specify_init_pose: true
    init_pos_x: 0.0
    init_pos_y: 0.0
    init_pos_z: 0.0
    init_ori_w: 1.0
    init_ori_x: 0.0
    init_ori_y: 0.0
    init_ori_z: 0.0

